### Site
repository: DuyKhoiCoder30062004/DuyKhoiCoder30062004.github.io
favicon: images/IMG_0514.JPG

### Content configuration version
version: 2

### Personal info
name: Đào Duy Anh Khôi
title: Seeking Internship
email: anhkhoi.bo@gmail.com
phone: (+84)915 62 1219
# website:

### Dark Mode (true/false/never)
darkmode: true

### Social links
github_username:  duykhoicoder30062004
linkedin_username: khoi-duy-a2812a24a
# twitter_username:
# dribbble_username:
# facebook_username:
# flickr_username:
# instagram_username:
# xing_username:
# pinterest_username:
# youtube_username:
# googleplus_username:
# orcid_username:

### Additional icon links
# additional_links:
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

#####################
### About Section ###
#####################
about_title: About
about_profile_image: images/IMG_0514.JPG
about_content: |
  Hi, I'm Khoi! 👋

  I'm a proactive Software Engineering undergraduate with a strong passion for Backend programming, Desktop development and Framework-based applications. I continuously expand my expertise in Software Engineering and AI through personal projects and dedicated learning.
  Currently, I'm seeking an internship where I can apply my technical skills, contribute meaningful value and grow professionally within a supportive environment.

##############
### Resume ###
##############
content:
  #######################
  ### Work Experience ###
  #######################
  - title: Work Experience
    layout: list
    content:
      - layout: left
        title: 
        sub_title: 
        caption: 
        link: 
        link_text: 
        quote: >
          IT.
        description: |
          <mark>Linux Server</mark> <mark>Docker</mark> <mark>Go/Bash/Python</mark> <mark>FastPanel</mark>

          - M
          
  #################
  ### Education ###
  #################
  - title: Education
    layout: list
    content:
      - layout: left
        title: Saigon University (SGU)
        caption: 2022 - Ongoing
        sub_title: BSc Information Technology<br>Specialization: Software Engineering
        # quote: >
        #
        description: |
          During my time at SGU I learnt most of key skills such as teamworking and meeting project deadlines, ensuring timely delivery. I truly enjoyed my time as a university student, where the campus culture fostered a healthy work-life balance.

  ################
  ### Projects ###
  ################
  - title: Projects
    layout: list
    content:

      #############
      ### Quizz ###
      #############
      - layout: top-middle
        border: weak
        title: Q
        sub_title: Backend Developer
        link: 
        # link_text: visit
        quote: >
          Q.
        description: |
          <div align="center">
            <img align="center" width="70%" src="./prjimg/" />
          </div>

          I .

          <mark>JavaFX</mark> <mark>Socket</mark> <mark>Multithreading</mark> <mark>MariaDB/MySQL</mark> <mark>Networking</mark> <mark>Excel Processing</mark>

      ###################
      ### Go Projects ###
      ###################
      - layout: top-middle
        border: weak
        title: Go Projects
        sub_title: Primary Developer
        # link: github.com/ttasc
        # link_text: visit
        additional_links:
          - title:  sgublogsite
            icon:   fab fa-github
            url:    github.com/ttasc/sgublogsite
          - title:  craftt
            icon:   fab fa-github
            url:    github.com/ttasc/craftt
        quote: >
          T.
        description: |
          <div align="center">
            <img align="center" width="70%" src="./" />
          </div>

          **[s](https://github.com)**: D.
            - <mark>Go</mark> <mark>Chi</mark> <mark>HTMX</mark> <mark>MariaDB/MySQL</mark>

          <br/>

          <div align="center">
            <img align="center" width="70%" src="./prjimg/craftt.png" />
          </div>
          **[c](https://github.com)** w.
            - <mark>Go</mark> <mark>Process handling</mark> <mark>WebSocket</mark> <mark>TLS</mark>

      #############
      ### anett ###
      #############
      - layout: top-middle
        border: weak
        title: anett
        sub_title: Primary Developer
        link: github.com/ttasc/anett
        # link_text: visit
        quote: >
          Dockerized Local Service Deployment Toolkit
        description: |
          T.

          <mark>Linux Server</mark> <mark>Docker</mark> <mark>Shell</mark> <mark>TUI</mark> <mark>Networking</mark>

      ################
      ### Dotfiles ###
      ################
      - layout: top-middle
        title: Dotfiles
        sub_title: Explorer & Developer
        link: github.com/ttasc/Dotfiles
        # link_text: visit
        quote: >
          My Workflow Optimization: Minimal, performance-focused. Extremely fast and small without sacrificing convenience.
        description: |
          <div align="center">
            <img align="center" width="70%" src="./prjimg/Dotfiles.png" />
          </div>
          I started exploring the world of Linux when I first entered high school. After a period of using Windows and gaining some experience in troubleshooting and problem-solving, I decided to switch to a new home - GNU/Linux. Through my journey with multiple Linux distributions and continuous exploration, I gained a deeper understanding of many computer-related concepts, including hardware, networking, and how an operating system works. I also started learning programming and created my own development environment on Linux, which is my Dotfiles.

          <mark>Administration</mark> <mark>Troubleshooting</mark> <mark>Scripting</mark> <mark>Networking</mark> <mark>Modifying OSS</mark> <mark>Home server</mark>

  ###############
  ### Skills ####
  ###############
  - title: Skills
    layout: list
    content:
      - layout: right
        sub_title: Soft Skills
        caption: Team Collaboration, Self-learning, Attention to detail, Communication, Problem-solving
        description: |
          - **Front-end (Web)**
            - React.js, TypeScript, Tailwind CSS
          - **Back-end (Web)**
            - FastAPI (Python), Node.js
          - **Desktop Development**
            - C# (Winforms), Java (Swing), Python (Tkinter)
          - **Database**
            - PostgreSQL, Supabase, Microsoft SQL Server
          - **AI & Productivity Tools**
            - ChatGPT, Google AI Studio, Lovable, Microsoft Copilot
          - **DevOps & Tools**
            - Git/Github, Docker, Docker Compose, Vercel, Postman
          - **Practices**
            - Layered Architecture (three-layer), Object-Oriented Programming (OOP), System Design & Architecture
            
  ###############
  ### Hobbies ###
  ###############
  - title: When I’m Not At My Desk
    layout: text
    content: |
      Alongside my interests in Software Engineering, some of my other interests and hobbies are:
      - Teaching 
      - Chilling
      - Listening to music 
      - Reading
      - Learning musical instrument
      - Learning new languages

### Footer
footer_show_references: true
references_title: Ho Chi Minh City, Viet Nam

### Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
